<?php
$bz_data = array(
# type | string | note |dkp|tozone|order
0 => array('zone', 'Windmill Basement', 'Windmill Basement', '5', '0', '0'),
1 => array('boss', 'Hodu Hammertooth', 'Hodu Hammertooth(Hodu Hammerzahn)', '10', '1', '1'),
2 => array('boss', 'Geianth', 'Geianth(Knochenbrecher)', '10', '1', '2'),
3 => array('zone', 'Bloody Gallery', 'Bloody Gallery', '5', '0', '1'),
4 => array('boss', 'Count Hibara', 'Count Hibara(Graf Hibara)', '10', '4', '1'),
5 => array('zone', 'Forsaken Abbey', 'Forsaken Abbey', '5', '0', '2'),
6 => array('boss', 'Ghoul Duke', 'Ghoul Duke(Ghul Duke)', '10', '6', '1'),
7 => array('boss', 'Flowing Chaos', 'Flowing Chaos(Fließendes Chaos)', '10', '6', '2'),
8 => array('boss', 'Hollow Shell', 'Hollow Shell(Leere Hülle)', '10', '6', '3'),
9 => array('boss', 'Cruel Eater', 'Cruel Eater(Gräuelfresser)', '10', '6', '4'),
10 => array('boss', 'Demon Witch Ancalon', 'Demon Witch Ancalon', '10', '6', '5'),
11 => array('zone', 'Necropolis of Mirrors', 'Necropolis of Mirrors', '10', '0', '3'),
12 => array('boss', 'Magister Gumas', 'Magister Gumas', '15', '12', '1'),
13 => array('boss', 'Androlier\'s Prisoner', 'Androlier\'s Prisoner(Androliers Gefangener)', '15', '12', '2'),
14 => array('boss', 'Androlier\'s Shadow', 'Androlier\'s Shadow(Androliers Schatten)', '15', '12', '3'),
15 => array('boss', 'Androlier\'s Strength', 'Androlier\'s Strength(Androliers Stärke)', '15', '12', '4'),
16 => array('boss', 'Krodamar', 'Krodamar', '15', '12', '5'),
17 => array('boss', 'Krodamon', 'Krodamon', '15', '12', '6'),
18 => array('zone', 'Pasper\'s Shrine', 'Pasper\'s Shrine', '15', '0', '4'),
19 => array('boss', 'Blackhorn Nisorn', 'Blackhorn Nisorn(Schwarzhorn Nisorn)', '20', '19', '1'),
20 => array('boss', 'Blackhorn Hafiz', 'Blackhorn Hafiz(Schwarzhorn Hafiz)', '20', '19', '2'),
21 => array('boss', 'Blackhorn Dorglas', 'Blackhorn Dorglas(Schwarzhorn-Dorglas)', '20', '19', '3'),
22 => array('boss', 'Blackhorn Bareth', 'Blackhorn Bareth(Schwarzhorn Bareth)', '20', '19', '4'),
23 => array('boss', 'Blackhorn Afalen', 'Blackhorn Afalen(Schwarzhorn Afalen)', '20', '19', '5'),
24 => array('zone', 'Mystic Altar', 'Mystic Altar', '15', '0', '5'),
25 => array('boss', 'Cursed Iron Golem', 'Cursed Iron Golem(Verwünschter Eisengolem)', '20', '25', '1'),
26 => array('boss', 'Razeela', 'Razeela', '20', '25', '2'),
27 => array('boss', 'Aukuda', 'Aukuda', '20', '25', '3'),
28 => array('boss', 'Dorlos', 'Dorlos', '20', '25', '4'),
29 => array('zone', 'Cyclops Lair', 'Cyclops Lair', '15', '0', '6'),
30 => array('boss', 'Boddosh', 'Boddosh(Podag)', '25', '30', '1'),
31 => array('boss', 'Zurhidon Negotiator', 'Zurhidon Negotiator(Zurhidon-Unterhändler)', '25', '30', '2'),
32 => array('boss', 'Ordig', 'Ordig(Ortiga)', '25', '30', '3'),
34 => array('boss', 'Masso', 'Masso(Matthew)', '25', '30', '4'),
35 => array('boss', 'Gorn', 'Gorn(Gaia)', '25', '30', '5'),
36 => array('boss', 'Uguda', 'Uguda(Wagoda)', '25', '30', '6'),
37 => array('zone', 'Kalin Shrine', 'Kalin Shrine', '20', '0', '7'),
38 => array('boss', 'Iron Rune Warrior', 'Iron Rune Warrior(Eisenrunenkrieger)', '30', '36', '1'),
39 => array('boss', 'Yusalien', 'Yusalien', '30', '36', '2'),
40 => array('boss', 'Locatha', 'Locatha', '30', '36', '3'),
41 => array('boss', 'Goddess of Art\'s Disciple', 'Goddess of Art\'s Disciple(Adept der Göttin)', '30', '36', '4'),
42 => array('boss', 'Ensia', 'Ensia', '30', '36', '5'),
43 => array('boss', 'Regin', 'Regin', '30', '36', '6')
);
?>