<?php
$bz_data = array(
# type | string | note |dkp|tozone|order
0 => array('zone', 'Windmill Basement', 'Windmill Basement', '5', '0', '0'),
1 => array('boss', 'Hodu Hammertooth', 'Hodu Hammertooth', '10', '1', '1'),
2 => array('boss', 'Geianth', 'Geianth', '10', '1', '2'),
3 => array('zone', 'Bloody Gallery', 'Bloody Gallery', '5', '0', '1'),
4 => array('boss', 'Count Hibara', 'Count Hibara', '10', '4', '1'),
5 => array('zone', 'Forsaken Abbey', 'Forsaken Abbey', '5', '0', '2'),
6 => array('boss', 'Ghoul Duke', 'Ghoul Duke', '10', '6', '1'),
7 => array('boss', 'Flowing Chaos', 'Flowing Chaos', '10', '6', '2'),
8 => array('boss', 'Hollow Shell', 'Hollow Shell', '10', '6', '3'),
9 => array('boss', 'Cruel Eater', 'Cruel Eater', '10', '6', '4'),
10 => array('boss', 'Demon Witch Ancalon', 'Demon Witch Ancalon', '10', '6', '5'),
11 => array('zone', 'Necropolis of Mirrors ', 'Necropolis of Mirrors', '10', '0', '3'),
12 => array('boss', 'Magister Gumas', 'Magister Gumas', '15', '12', '1'),
13 => array('boss', 'Androlier\'s Prisoner', 'Androlier\'s Prisoner', '15', '12', '2'),
14 => array('boss', 'Androlier\'s Shadow', 'Androlier\'s Shadow', '15', '12', '3'),
15 => array('boss', 'Androlier\'s Strength', 'Androlier\'s Strength', '15', '12', '4'),
16 => array('boss', 'Krodamar', 'Krodamar', '15', '12', '5'),
17 => array('boss', 'Krodamon', 'Krodamon', '15', '12', '6'),
18 => array('zone', 'Pasper\'s Shrine', 'Pasper\'s Shrine', '15', '0', '4'),
19 => array('boss', 'Blackhorn Nisorn', 'Blackhorn Nisorn', '20', '19', '1'),
20 => array('boss', 'Blackhorn Hafiz', 'Blackhorn Hafiz', '20', '19', '2'),
21 => array('boss', 'Blackhorn Dorglas', 'Blackhorn Dorglas', '20', '19', '3'),
22 => array('boss', 'Blackhorn Bareth', 'Blackhorn Bareth', '20', '19', '4'),
23 => array('boss', 'Blackhorn Afalen', 'Blackhorn Afalen', '20', '19', '5'),
24 => array('zone', 'Mystic Altar', 'Pasper\'s Shrine', '15', '0', '5'),
25 => array('boss', 'Cursed lron Golem', 'Cursed lron Golem', '20', '25', '1'),
26 => array('boss', 'Razeela', 'Razeela', '20', '25', '2'),
27 => array('boss', 'Aukuda, the Cursed', 'Aukuda, the Cursed', '20', '25', '3'),
28 => array('boss', 'Dorlos', 'Dorlos', '20', '25', '4'),
29 => array('zone', 'Cyclops Lair', 'Pasper\'s Shrine', '15', '0', '6'),
30 => array('boss', 'Boddosh', 'Boddosh', '25', '30', '1'),
31 => array('boss', 'Zurhidon Negotiator', 'Zurhidon Negotiator', '25', '30', '2'),
32 => array('boss', 'Ordig', 'Ordig', '25', '30', '3'),
33 => array('boss', 'Gaja', 'Gaja', '25', '30', '4'),
34 => array('boss', 'Uguda', 'Uguda', '25', '30', '5'),
35 => array('zone', 'Kalin Shrine', 'Kalin Shrine', '20', '0', '7'),
36 => array('boss', 'Iron Rune Warrior', 'Iron Rune Warrior', '30', '36', '1'),
37 => array('boss', 'Yusalien', 'Yusalien', '30', '36', '2'),
38 => array('boss', 'Locatha', 'Locatha', '30', '36', '3'),
39 => array('boss', 'Goddess of Art\'s Disciple', 'Goddess of Art\'s Disciple', '30', '36', '4'),
40 => array('boss', 'Ensia', 'Ensia', '30', '36', '5'),
41 => array('boss', 'Regin', 'Regin', '30', '36', '6')
);
?>